---
- hosts: dev
  user: harm
  sudo: yes
  tasks:
    - apt: pkg=$item state=installed
      with_items:
        - apt-file
        - htop
        - dnsutils
        - curl
        - ack-grep
        - tmux
        - unattended-upgrades
        - build-essential
    - name: Add packages for future Ansibles
      apt: pkg=$item state=installed
      with_items:
        - python-yaml
        - python-jinja2
        - python-paramiko
        - sshpass
    - name: Copy the unattended upgrades file
      copy: src=files/50unattended-upgrades dest=/etc/apt/apt.conf.d/49unattended-upgrades

