---
- hosts: dev
  user: harm
  sudo: yes
  tasks:
    - name: add Brightbox PPA and install Ruby
      apt: pkg=python-software-properties state=installed update-cache=yes
    - command: apt-add-repository ppa:brightbox/ruby-ng-experimental -y
    - apt: pkg=ruby1.9.3 update-cache=yes state=installed
    - name: install default gems
      gem: name=bundler state=present
    - gem: name=pry state=present
