---
- hosts: dev
  user: harm
  sudo: yes
  tasks:
    - apt: pkg=$item state=installed
      with_items:
        - apt-file
        - htop
        - dnsutils
        - curl
        - ack-grep
        - tmux
        - unattended-upgrades
    - name: Add packages for future Ansibles
      apt: pkg=$item state=installed
      with_items:
        - python-yaml
        - python-jinja2
        - python-paramiko
    - name: Add S3QL PPA for my remote drive
      command: add-apt-repository ppa:nikratio/s3ql -y
    - name: Install S3QL
      apt: pkg=s3ql update-cache=yes state=installed
    - name: Copy the unattended upgrades file
      copy: src=files/unattended-upgrades dest=/etc/apt/apt.conf.d/49unattended-upgrades

