---
- hosts: dev
  user: harm
  sudo: yes
  tasks:
    - command: apt-get clean
    - apt: update_cache=yes
    - name: add Brightbox PPA and install Ruby
      apt: pkg=software-properties-common state=installed update-cache=yes
    - command: apt-add-repository ppa:brightbox/ruby-ng-experimental -y
    - apt: pkg=ruby2.0 update-cache=yes state=installed
    - gem: name=bundler state=present
    - gem: name=pry state=present
